version: '3.8'

services: 
  app:
    image: claimbook
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"  
    environment:
      - DB_HOST=mysql-container
      - DB_PORT=3303
      - DB_NAME=test
      - DB_USER=user
      - DB_PASSWORD=user
    networks:
      - app-network

networks:
  app-network:
    external: true     